Repository PyGEM-Community/PyGEM, pull requests merged in 2025-03, with the labels that each got.

#63 Test PyGEM-notebooks in CI
  .github/workflows/test_suite.yml
  pygem/tests/test_notebooks.py
  pyproject.toml
Labels: testing

#79 Expand `ConfigManager` tests
  .github/workflows/test_suite.yml
  pygem/setup/config.py
  pygem/tests/test_config.py
  pygem/tests/test_notebooks.py
  pygem/tests/test_oggm_compat.py
  pyproject.toml
Labels: testing

#78 `ConfigManager` class with `update_config` functionality
  .github/workflows/test_suite.yml
  pygem/bin/op/duplicate_gdirs.py
  pygem/bin/op/initialize.py
  pygem/bin/op/list_failed_simulations.py
  pygem/bin/postproc/postproc_binned_monthly_mass.py
  pygem/bin/postproc/postproc_compile_simulations.py
  pygem/bin/postproc/postproc_distribute_ice.py
  pygem/bin/postproc/postproc_monthly_mass.py
  pygem/bin/preproc/preproc_fetch_mbdata.py
  pygem/bin/preproc/preproc_wgms_estimate_kp.py
  pygem/bin/run/run_calibration.py
  pygem/bin/run/run_calibration_frontalablation.py
  pygem/bin/run/run_calibration_reg_glena.py
  pygem/bin/run/run_mcmc_priors.py
  pygem/bin/run/run_simulation.py
  pygem/class_climate.py
  pygem/gcmbiasadj.py
  pygem/glacierdynamics.py
  pygem/massbalance.py
  pygem/mcmc.py
  pygem/oggm_compat.py
  pygem/output.py
  pygem/pygem_modelsetup.py
  pygem/setup/config.py
  pygem/shop/debris.py
  pygem/shop/icethickness.py
  pygem/shop/mbdata.py
  pygem/shop/oib.py
  pygem/tests/test_config.py
  pygem/tests/test_notebooks.py
  pygem/utils/_funcs.py
Labels: enhancement, refactor

#81 CLI argument to specify custom output simulation filename suffix
  pygem/bin/run/run_simulation.py
  pygem/output.py
  pygem/setup/config.py
  pygem/setup/config.yaml
Labels: enhancement

#84 Contribution guide
  README.md
  docs/contributing.md
  docs/dev.md
  docs/index.rst
  docs/install_pygem.md
  docs/pygem_environment.yml
  pyproject.toml
Labels: documentation

#87 Source version # for documentation from pyproject.toml
  docs/conf.py
Labels: documentation
